name: jerry-ai-app
displayName: jerry-ai-app CI
triggers:
  push:
    branches:
      precise:
        - jerrydev
        - main

stages:
  - stage:
    name: install
    displayName: 安装依赖
    strategy: naturally
    trigger: auto
    steps:
      - step: build@nodejs
        name: install_deps
        displayName: 安装依赖
        nodeVersion: "20"
        commands:
          - npm install -g pnpm
          - pnpm install --frozen-lockfile

  - stage:
    name: lint
    displayName: 代码检查
    strategy: naturally
    trigger: auto
    steps:
      - step: build@nodejs
        name: eslint
        displayName: ESLint 检查
        nodeVersion: "20"
        commands:
          - npm install -g pnpm
          - pnpm install --frozen-lockfile
          - cd servers/miaoma-llm-server && npx eslint src/

  - stage:
    name: build
    displayName: 构建
    strategy: naturally
    trigger: auto
    steps:
      - step: build@nodejs
        name: build_server
        displayName: 后端构建
        nodeVersion: "20"
        commands:
          - npm install -g pnpm
          - pnpm install --frozen-lockfile
          - cd servers/miaoma-llm-server && pnpm build

  - stage:
    name: test
    displayName: 测试
    strategy: naturally
    trigger: auto
    steps:
      - step: build@nodejs
        name: run_test
        displayName: 后端测试
        nodeVersion: "20"
        commands:
          - npm install -g pnpm
          - pnpm install --frozen-lockfile
          - cd servers/miaoma-llm-server && pnpm test
