import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1781687393264 implements MigrationInterface {
    name = 'InitialSchema1781687393264'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`users\` (\`id\` int NOT NULL AUTO_INCREMENT, \`email\` varchar(255) NULL, \`phone\` varchar(20) NULL, \`username\` varchar(50) NULL, \`password\` varchar(255) NOT NULL, \`avatar\` varchar(500) NULL, \`isActive\` tinyint NOT NULL DEFAULT 1, \`tokenVersion\` int NOT NULL DEFAULT '0', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_97672ac88f789774dd47f7c8be\` (\`email\`), UNIQUE INDEX \`IDX_a000cca60bcf04454e72769949\` (\`phone\`), UNIQUE INDEX \`IDX_fe0bb3f6520ee0469504521e71\` (\`username\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_memory\` (\`id\` int NOT NULL AUTO_INCREMENT, \`content\` text NOT NULL, \`category\` varchar(255) NOT NULL DEFAULT 'fact', \`sourceSessionId\` varchar(255) NULL, \`userId\` varchar(255) NOT NULL DEFAULT 'default', \`importance\` int NOT NULL DEFAULT '3', \`accessCount\` int NOT NULL DEFAULT '0', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tool_usage\` (\`id\` int NOT NULL AUTO_INCREMENT, \`userId\` varchar(255) NOT NULL DEFAULT 'default', \`sessionId\` varchar(255) NULL, \`toolName\` varchar(255) NOT NULL, \`success\` tinyint NOT NULL DEFAULT 1, \`durationMs\` int NOT NULL DEFAULT '0', \`paramsSummary\` text NULL, \`errorMessage\` text NULL, \`modelId\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX \`IDX_3c9373ed999c0f8a17b6a45442\` (\`userId\`), INDEX \`IDX_62d91cd4e2d19dbd0e6ab63b1c\` (\`sessionId\`), INDEX \`IDX_7e0d4ccc241eca416f361d53a6\` (\`toolName\`), INDEX \`IDX_3a569f469b89c20feb23f38b29\` (\`createdAt\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`session\` (\`id\` int NOT NULL AUTO_INCREMENT, \`sessionId\` varchar(255) NOT NULL, \`title\` varchar(255) NOT NULL, \`userId\` varchar(255) NOT NULL, \`isPinned\` tinyint NOT NULL DEFAULT 0, \`tags\` text NULL, \`category\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_6f8fc3d2111ccc30d98e173d8d\` (\`sessionId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`session_summary\` (\`id\` int NOT NULL AUTO_INCREMENT, \`sessionId\` varchar(255) NOT NULL, \`summaryContent\` text NOT NULL, \`coveredMessageCount\` int NOT NULL DEFAULT '0', \`userId\` varchar(255) NOT NULL DEFAULT 'default', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_16386992cbe33de31cea52e02e\` (\`sessionId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`pending_vector_ops\` (\`id\` int NOT NULL AUTO_INCREMENT, \`versionId\` int NOT NULL, \`operation\` enum ('remove', 'update_status', 'reindex') NOT NULL, \`status\` enum ('pending', 'processing', 'completed', 'failed') NOT NULL DEFAULT 'pending', \`retryCount\` int NOT NULL DEFAULT '0', \`errorMessage\` text NULL, \`params\` text NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX \`IDX_feb134b3a9ce0a95e36fdcf857\` (\`createdAt\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`message_feedback\` (\`id\` int NOT NULL AUTO_INCREMENT, \`userId\` varchar(255) NOT NULL DEFAULT 'default', \`sessionId\` varchar(255) NOT NULL, \`userMessage\` text NOT NULL, \`assistantMessage\` text NOT NULL, \`rating\` varchar(255) NOT NULL, \`comment\` text NULL, \`modelId\` varchar(255) NULL, \`usedKnowledgeBase\` tinyint NOT NULL DEFAULT 0, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`llm_usage\` (\`id\` int NOT NULL AUTO_INCREMENT, \`userId\` varchar(255) NOT NULL DEFAULT 'default', \`sessionId\` varchar(255) NULL, \`modelId\` varchar(255) NOT NULL, \`inputTokens\` int NOT NULL DEFAULT '0', \`outputTokens\` int NOT NULL DEFAULT '0', \`historyCount\` int NOT NULL DEFAULT '0', \`usedKnowledgeBase\` tinyint NOT NULL DEFAULT 0, \`imageCount\` int NOT NULL DEFAULT '0', \`responseTimeMs\` int NULL, \`userMessage\` text NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`knowledge_source_sync_logs\` (\`id\` int NOT NULL AUTO_INCREMENT, \`sourceId\` int NOT NULL, \`status\` enum ('running', 'success', 'failed') NOT NULL, \`pagesFetched\` int NOT NULL DEFAULT '0', \`chunksAdded\` int NOT NULL DEFAULT '0', \`chunksUpdated\` int NOT NULL DEFAULT '0', \`pagesNew\` int NOT NULL DEFAULT '0', \`pagesUpdated\` int NOT NULL DEFAULT '0', \`pagesDeleted\` int NOT NULL DEFAULT '0', \`updatedPageDetails\` text NULL, \`errorMessage\` text NULL, \`startedAt\` timestamp NULL, \`finishedAt\` timestamp NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX \`IDX_b4824fd3b2935b9ed6a552e9f6\` (\`createdAt\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`knowledge_sources\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`type\` enum ('web', 'feishu') NOT NULL, \`config\` text NULL, \`syncInterval\` int NOT NULL DEFAULT '60', \`lastSyncStatus\` enum ('idle', 'syncing', 'success', 'failed') NOT NULL DEFAULT 'idle', \`lastSyncAt\` timestamp NULL, \`lastSyncError\` text NULL, \`enabled\` tinyint NOT NULL DEFAULT 1, \`hasContentUpdate\` tinyint NOT NULL DEFAULT 0, \`maxDepth\` int NOT NULL DEFAULT '2', \`maxPages\` int NOT NULL DEFAULT '50', \`preferMarkdown\` tinyint NOT NULL DEFAULT 1, \`enableJsRendering\` tinyint NOT NULL DEFAULT 0, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`knowledge_source_pages\` (\`id\` int NOT NULL AUTO_INCREMENT, \`sourceId\` int NOT NULL, \`pageKey\` varchar(500) NOT NULL, \`pageTitle\` varchar(500) NOT NULL, \`contentHash\` varchar(32) NOT NULL, \`pageUrl\` text NULL, \`isDeleted\` tinyint NOT NULL DEFAULT 0, \`syncedAt\` timestamp NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`IDX_69bf6e9b9d5ab5a486e7e0c3af\` (\`sourceId\`), UNIQUE INDEX \`IDX_b0a380aef0b901c9306be5351f\` (\`sourceId\`, \`pageKey\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`generated_document\` (\`id\` int NOT NULL AUTO_INCREMENT, \`key\` varchar(255) NOT NULL, \`userId\` varchar(255) NOT NULL DEFAULT 'default', \`sessionId\` varchar(255) NULL, \`filename\` varchar(255) NOT NULL, \`format\` varchar(16) NOT NULL, \`mimeType\` varchar(255) NOT NULL, \`sizeBytes\` bigint NOT NULL DEFAULT '0', \`filePath\` varchar(255) NOT NULL, \`checksum\` varchar(64) NULL, \`lastAccessedAt\` datetime NULL, \`expiresAt\` datetime NOT NULL, \`favorited\` tinyint NOT NULL DEFAULT 0, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`IDX_e8ec1d6c84c156a562da5bc42e\` (\`userId\`), INDEX \`IDX_538a772d4636ecbbd64579afcd\` (\`sessionId\`), INDEX \`IDX_480ce45b4149c26618173d38aa\` (\`lastAccessedAt\`), INDEX \`IDX_e0fd9b83a432b998275a6e10af\` (\`expiresAt\`), INDEX \`IDX_1d8e320dd46897abfd35196122\` (\`favorited\`), UNIQUE INDEX \`IDX_b6877ceb04e67c36d44537f574\` (\`key\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`document_audit_logs\` (\`id\` int NOT NULL AUTO_INCREMENT, \`documentId\` int NOT NULL, \`versionId\` int NULL, \`action\` enum ('upload', 'activate', 'archive', 'rollback', 'delete') NOT NULL, \`operator\` varchar(100) NOT NULL DEFAULT 'anonymous', \`detail\` text NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX \`IDX_bfd7af54d5108a6d40266b9056\` (\`createdAt\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`documents\` (\`id\` int NOT NULL AUTO_INCREMENT, \`title\` varchar(255) NOT NULL, \`description\` text NULL, \`tags\` text NULL, \`currentVersionId\` int NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`document_versions\` (\`id\` int NOT NULL AUTO_INCREMENT, \`documentId\` int NOT NULL, \`versionNumber\` int NOT NULL, \`fileUrl\` varchar(500) NOT NULL, \`fileSize\` bigint NOT NULL, \`fileType\` varchar(50) NOT NULL, \`checksum\` varchar(64) NULL, \`status\` enum ('draft', 'active', 'archived') NOT NULL DEFAULT 'draft', \`parsingStatus\` enum ('pending', 'parsing', 'success', 'failed') NOT NULL DEFAULT 'pending', \`errorMessage\` text NULL, \`chunkCount\` int NOT NULL DEFAULT '0', \`uploadedBy\` varchar(100) NULL, \`archivedAt\` timestamp NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX \`IDX_476b04254e120c94093ea77ae7\` (\`createdAt\`), INDEX \`IDX_b2e52ab599326ef28726a022da\` (\`parsingStatus\`), INDEX \`IDX_ab517e08fd5246f56324d29ba9\` (\`status\`), UNIQUE INDEX \`IDX_4a39e3b4501012b58a484a3488\` (\`documentId\`, \`versionNumber\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`chat_history\` (\`id\` int NOT NULL AUTO_INCREMENT, \`userId\` varchar(255) NOT NULL, \`sessionId\` varchar(255) NOT NULL, \`role\` varchar(255) NOT NULL, \`content\` text NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`auto_evaluation\` (\`id\` int NOT NULL AUTO_INCREMENT, \`userId\` varchar(255) NOT NULL DEFAULT 'default', \`sessionId\` varchar(255) NOT NULL, \`userMessage\` text NOT NULL, \`assistantMessage\` text NOT NULL, \`score\` float NOT NULL DEFAULT '0', \`reason\` text NULL, \`dimension\` varchar(255) NOT NULL DEFAULT 'relevance', \`modelId\` varchar(255) NULL, \`usedKnowledgeBase\` tinyint NOT NULL DEFAULT 0, \`responseTimeMs\` int NOT NULL DEFAULT '0', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`knowledge_source_sync_logs\` ADD CONSTRAINT \`FK_18fc057ef499260191907056986\` FOREIGN KEY (\`sourceId\`) REFERENCES \`knowledge_sources\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`knowledge_source_pages\` ADD CONSTRAINT \`FK_69bf6e9b9d5ab5a486e7e0c3af8\` FOREIGN KEY (\`sourceId\`) REFERENCES \`knowledge_sources\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`document_audit_logs\` ADD CONSTRAINT \`FK_2570996df7722de7f46a21c0592\` FOREIGN KEY (\`documentId\`) REFERENCES \`documents\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`document_versions\` ADD CONSTRAINT \`FK_4ea14bf55da75a8c3997e745a28\` FOREIGN KEY (\`documentId\`) REFERENCES \`documents\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`document_versions\` DROP FOREIGN KEY \`FK_4ea14bf55da75a8c3997e745a28\``);
        await queryRunner.query(`ALTER TABLE \`document_audit_logs\` DROP FOREIGN KEY \`FK_2570996df7722de7f46a21c0592\``);
        await queryRunner.query(`ALTER TABLE \`knowledge_source_pages\` DROP FOREIGN KEY \`FK_69bf6e9b9d5ab5a486e7e0c3af8\``);
        await queryRunner.query(`ALTER TABLE \`knowledge_source_sync_logs\` DROP FOREIGN KEY \`FK_18fc057ef499260191907056986\``);
        await queryRunner.query(`DROP TABLE \`auto_evaluation\``);
        await queryRunner.query(`DROP TABLE \`chat_history\``);
        await queryRunner.query(`DROP INDEX \`IDX_4a39e3b4501012b58a484a3488\` ON \`document_versions\``);
        await queryRunner.query(`DROP INDEX \`IDX_ab517e08fd5246f56324d29ba9\` ON \`document_versions\``);
        await queryRunner.query(`DROP INDEX \`IDX_b2e52ab599326ef28726a022da\` ON \`document_versions\``);
        await queryRunner.query(`DROP INDEX \`IDX_476b04254e120c94093ea77ae7\` ON \`document_versions\``);
        await queryRunner.query(`DROP TABLE \`document_versions\``);
        await queryRunner.query(`DROP TABLE \`documents\``);
        await queryRunner.query(`DROP INDEX \`IDX_bfd7af54d5108a6d40266b9056\` ON \`document_audit_logs\``);
        await queryRunner.query(`DROP TABLE \`document_audit_logs\``);
        await queryRunner.query(`DROP INDEX \`IDX_b6877ceb04e67c36d44537f574\` ON \`generated_document\``);
        await queryRunner.query(`DROP INDEX \`IDX_1d8e320dd46897abfd35196122\` ON \`generated_document\``);
        await queryRunner.query(`DROP INDEX \`IDX_e0fd9b83a432b998275a6e10af\` ON \`generated_document\``);
        await queryRunner.query(`DROP INDEX \`IDX_480ce45b4149c26618173d38aa\` ON \`generated_document\``);
        await queryRunner.query(`DROP INDEX \`IDX_538a772d4636ecbbd64579afcd\` ON \`generated_document\``);
        await queryRunner.query(`DROP INDEX \`IDX_e8ec1d6c84c156a562da5bc42e\` ON \`generated_document\``);
        await queryRunner.query(`DROP TABLE \`generated_document\``);
        await queryRunner.query(`DROP INDEX \`IDX_b0a380aef0b901c9306be5351f\` ON \`knowledge_source_pages\``);
        await queryRunner.query(`DROP INDEX \`IDX_69bf6e9b9d5ab5a486e7e0c3af\` ON \`knowledge_source_pages\``);
        await queryRunner.query(`DROP TABLE \`knowledge_source_pages\``);
        await queryRunner.query(`DROP TABLE \`knowledge_sources\``);
        await queryRunner.query(`DROP INDEX \`IDX_b4824fd3b2935b9ed6a552e9f6\` ON \`knowledge_source_sync_logs\``);
        await queryRunner.query(`DROP TABLE \`knowledge_source_sync_logs\``);
        await queryRunner.query(`DROP TABLE \`llm_usage\``);
        await queryRunner.query(`DROP TABLE \`message_feedback\``);
        await queryRunner.query(`DROP INDEX \`IDX_feb134b3a9ce0a95e36fdcf857\` ON \`pending_vector_ops\``);
        await queryRunner.query(`DROP TABLE \`pending_vector_ops\``);
        await queryRunner.query(`DROP INDEX \`IDX_16386992cbe33de31cea52e02e\` ON \`session_summary\``);
        await queryRunner.query(`DROP TABLE \`session_summary\``);
        await queryRunner.query(`DROP INDEX \`IDX_6f8fc3d2111ccc30d98e173d8d\` ON \`session\``);
        await queryRunner.query(`DROP TABLE \`session\``);
        await queryRunner.query(`DROP INDEX \`IDX_3a569f469b89c20feb23f38b29\` ON \`tool_usage\``);
        await queryRunner.query(`DROP INDEX \`IDX_7e0d4ccc241eca416f361d53a6\` ON \`tool_usage\``);
        await queryRunner.query(`DROP INDEX \`IDX_62d91cd4e2d19dbd0e6ab63b1c\` ON \`tool_usage\``);
        await queryRunner.query(`DROP INDEX \`IDX_3c9373ed999c0f8a17b6a45442\` ON \`tool_usage\``);
        await queryRunner.query(`DROP TABLE \`tool_usage\``);
        await queryRunner.query(`DROP TABLE \`user_memory\``);
        await queryRunner.query(`DROP INDEX \`IDX_fe0bb3f6520ee0469504521e71\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_a000cca60bcf04454e72769949\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_97672ac88f789774dd47f7c8be\` ON \`users\``);
        await queryRunner.query(`DROP TABLE \`users\``);
    }

}
